### ISSUE TITLE
Pas op met willekeur bij 'semantische' elementen

### ISSUE THREAD

**Issue by KrijnHoetmer** [roberrrt-s/grocery-fallback#3]
Kleinigheidje, maar `<section>`, `<main>` en `<aside>` hebben in principe een betekenis. Schroom niet om gewoon een `<div>` te gebruiken waar je nu bijvoorbeeld een `<aside>` gebruikt. Divitis is niet tof, maar de verkeerde elementen gebruiken is nog minder tof.

**Comment by KrijnHoetmer** [comment]
Wat doet `</section class="content">` ? :)

**Comment by KoopReynders** [comment]
done
