### ISSUE TITLE
Er ontbreekt nog wat markup om je 'basic state' te ondersteunen.

### ISSUE THREAD

**Issue by KrijnHoetmer** [roberrrt-s/grocery-fallback#4]
Ik kan nu wel op je checkboxjes en button klikken, maar dan gebeurt er volgens mij niets.

**Comment by roberrrt-s** [comment]
Heb nu een commit gedaan die het 'beoogde' effect simuleert, ik ben zelf niet vloeiend genoeg met node / php om te laten zien wat ik bedoel, maar hiermee impliceer ik dat ik dit op deze manier backend zo zou willen oplossen, effectief gezien de 'basic state'

**Comment by KrijnHoetmer** [comment]
Er ontbreekt nog steeds markup. Zet JS eens uit om te kijken wat er dan gebeurt als je op de knop klikt. (Back-end bouwen is natuurlijk niet nodig.)

**Comment by roberrrt-s** [comment]
Ah, een form en een submit event, waarom heb ik daar niet eerder aan gedacht.

(Deze toevoeging is puur voor mezelf, zodat ik het niet vergeet!)

**Comment by KoopReynders** [comment]
done
