### ISSUE TITLE
Wat gebeurt er in browsers die `classList` niet ondersteunen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [roberrrt-s/grocery-fallback#6]
IE8 of IE9 bijvoorbeeld.

**Comment by roberrrt-s** [comment]
classList was een enhancement, die ervoor zou zorgen dat de user feedback kreeg als hij over een element hoverde waarin je dingen kon droppen. Ik ben van plan om in m'n nieuwe versie (want, PE!) ook classList overbodig te maken, that is, als de browser dit niet ondersteunt!

**Comment by KrijnHoetmer** [comment]
Fair enough, maar ik bedoelde meer, wat gebeurt er nu in browsers die `classList` niet ondersteunen? Testen ajb!

**Comment by roberrrt-s** [comment]
Updated, classList is nu niet meer in de code terug te vinden, className is breder ondersteund en is nu ook in staat om deze aanpassingen te maken.

**Comment by KrijnHoetmer** [comment]
Dat kan ook, maar een simpele feature detect (Cutting the Mustard techniek) was ook goed geweest.

**Comment by KrijnHoetmer** [comment]
Ok, zelfde vraag dan voor `querySelectorAll` die je gebruikt in basic.js.

**Comment by roberrrt-s** [comment]
Dan krijg ik nu terug:

`Object doesn't support this property or method`

En daardoor werkt niets meer =/

**Comment by KoopReynders** [comment]
Antwoord was: Cutting the mustard
Time is up
