### ISSUE TITLE
Wat doe je met het `draggable` attribuut?

### ISSUE THREAD

**Issue by KrijnHoetmer** [roberrrt-s/grocery-fallback#7]
In je HTML zet je 'm op `false` en in je JS test je op `e.target.getAttribute('draggable') == "true"`, maar waar verander je dat?

**Comment by roberrrt-s** [comment]
Nergens, dit was een 'half omslachtige, semi semantisch correcte' manier van controleren welke elementen in het lijstje wel een drag verdienden. Ik ga dit aanpassen in een andere commit, en zal dit issue daarin meenemen, in m'n nieuwe versie zal dit namelijk niet meer nodig zijn.

**Comment by roberrrt-s** [comment]
Inmiddels ga ik deze in m'n nieuwe commit niet meer gebruiken in de javascript, en hebben de bijnodigde elementen een fatsoenlijke waarde bij het attribuut, zie opkomende commit ;)

**Comment by KoopReynders** [comment]
done
