### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [roberrrt-s/grocery-fallback#8]
Wat ik mis in je Readme is een gestructureerde opbouw van je verhaal.
B.v. beginnen met wát de opdracht/demo is, welke hippe API je daarvoor gaat gebruiken/onderzoeken, en dan stap voor stap hoe je de PE hebt gedaan ...

Readme mist een duidelijk opbouw. Zie Moodle voor oplevercriteria.

**Comment by roberrrt-s** [comment]
Extra toegevoegd:
- Diepgaande support voor t/m IE6 dankzij:
  - className ipv classList
  - attachEvent ipv addEventListener
  - HTML manipulatie puur op DOM level 2 niveau
- Support voor mensen zonder muis toegevoegd, tab + space zorgt ervoor dat de applicatie werkt. 
- Support voor mensen zonder zicht toegevoegd, dankzij tabs + labels

**Comment by KoopReynders** [comment]
done
